/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afa.foreveryuser;

/**
 *
 * @author ADI
 */
public class IndexForm extends javax.swing.JFrame {

    /**
     * Creates new form IndexForm
     */
    public IndexForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        ico_MoviePanel = new javax.swing.JLabel();
        Label_Title = new javax.swing.JLabel();
        Label_Subtitle = new javax.swing.JLabel();
        Panel_PrintTicket = new javax.swing.JPanel();
        ico_Print = new javax.swing.JLabel();
        Label_PrintTicket = new javax.swing.JLabel();
        Panel_OrderTicket = new javax.swing.JPanel();
        ico_Ticket = new javax.swing.JLabel();
        Label_OrderTicket = new javax.swing.JLabel();
        Label_Version = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 246));
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(255, 102, 0));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ico_MoviePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_MoviePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8_cinema_104px.png"))); // NOI18N
        topPanel.add(ico_MoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 100));

        Label_Title.setBackground(new java.awt.Color(51, 51, 51));
        Label_Title.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(255, 255, 255));
        Label_Title.setText("Welcome");
        topPanel.add(Label_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 170, 40));

        Label_Subtitle.setBackground(new java.awt.Color(51, 51, 51));
        Label_Subtitle.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_Subtitle.setForeground(new java.awt.Color(255, 255, 255));
        Label_Subtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Subtitle.setText("PISOW Cinema by AFA Inc.");
        topPanel.add(Label_Subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, 20));

        bg.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 1, 680, 80));

        Panel_PrintTicket.setBackground(new java.awt.Color(51, 51, 51));
        Panel_PrintTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_PrintTicketMouseClicked(evt);
            }
        });
        Panel_PrintTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ico_Print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8_print_52px_1.png"))); // NOI18N
        Panel_PrintTicket.add(ico_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 59));

        Label_PrintTicket.setBackground(new java.awt.Color(51, 51, 51));
        Label_PrintTicket.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_PrintTicket.setForeground(new java.awt.Color(255, 255, 255));
        Label_PrintTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_PrintTicket.setText("Print Ticket");
        Panel_PrintTicket.add(Label_PrintTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 130, -1));

        bg.add(Panel_PrintTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 150, 130));

        Panel_OrderTicket.setBackground(new java.awt.Color(51, 51, 51));
        Panel_OrderTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_OrderTicketMouseClicked(evt);
            }
        });
        Panel_OrderTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ico_Ticket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8_ticket_52px_2.png"))); // NOI18N
        Panel_OrderTicket.add(ico_Ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 59));

        Label_OrderTicket.setBackground(new java.awt.Color(51, 51, 51));
        Label_OrderTicket.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Label_OrderTicket.setForeground(new java.awt.Color(255, 255, 255));
        Label_OrderTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_OrderTicket.setText("Order Ticket");
        Panel_OrderTicket.add(Label_OrderTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 130, -1));

        bg.add(Panel_OrderTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 130));

        Label_Version.setBackground(new java.awt.Color(51, 51, 51));
        Label_Version.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Label_Version.setForeground(new java.awt.Color(255, 255, 255));
        Label_Version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Version.setText("Ver. 0.0.1 (Beta)");
        bg.add(Label_Version, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_OrderTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_OrderTicketMouseClicked
        // TODO add your handling code here:
        Restrict pesanTiket = new Restrict();
        this.dispose();
        pesanTiket.setVisible(true);
    }//GEN-LAST:event_Panel_OrderTicketMouseClicked

    private void Panel_PrintTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_PrintTicketMouseClicked
        // TODO add your handling code here:
        TicketPrintForm cetakTiket = new TicketPrintForm();
        this.dispose();
        cetakTiket.setVisible(true);
    }//GEN-LAST:event_Panel_PrintTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_OrderTicket;
    private javax.swing.JLabel Label_PrintTicket;
    private javax.swing.JLabel Label_Subtitle;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JLabel Label_Version;
    private javax.swing.JPanel Panel_OrderTicket;
    private javax.swing.JPanel Panel_PrintTicket;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel ico_MoviePanel;
    private javax.swing.JLabel ico_Print;
    private javax.swing.JLabel ico_Ticket;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
