/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afa.foreveryuser;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ajitrinioferi
 */
public class SelectSeat extends javax.swing.JFrame {

    private Ticketing tc;
    private String scheduleid;
    private String Strseat;
    ArrayList<String> seat = new ArrayList<String>();

    /**
     * Creates new form SelectSeat
     */
    public SelectSeat(Ticketing tc, String scheduleid) {
        initComponents();
        this.tc = tc;
        this.scheduleid = scheduleid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Label_A = new javax.swing.JLabel();
        Label_B = new javax.swing.JLabel();
        Label_C = new javax.swing.JLabel();
        Label_D = new javax.swing.JLabel();
        Label_E = new javax.swing.JLabel();
        Label_F = new javax.swing.JLabel();
        Label_1 = new javax.swing.JLabel();
        Label_2 = new javax.swing.JLabel();
        Label_3 = new javax.swing.JLabel();
        Label_4 = new javax.swing.JLabel();
        Label_5 = new javax.swing.JLabel();
        Label_6 = new javax.swing.JLabel();
        Label_7 = new javax.swing.JLabel();
        Label_8 = new javax.swing.JLabel();
        Label_9 = new javax.swing.JLabel();
        Label_10 = new javax.swing.JLabel();
        Label_11 = new javax.swing.JLabel();
        confirmpanel = new javax.swing.JPanel();
        btn_seat = new javax.swing.JButton();
        Label_Confirm = new javax.swing.JLabel();
        enter = new javax.swing.JLabel();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        F9 = new javax.swing.JButton();
        F10 = new javax.swing.JButton();
        F11 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        E9 = new javax.swing.JButton();
        E10 = new javax.swing.JButton();
        E11 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        D9 = new javax.swing.JButton();
        D10 = new javax.swing.JButton();
        D11 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        C11 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        ico_Exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(218, 199));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_A.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_A.setForeground(new java.awt.Color(255, 102, 0));
        Label_A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_A.setText("A");
        bg.add(Label_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, 20));

        Label_B.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_B.setForeground(new java.awt.Color(255, 102, 0));
        Label_B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_B.setText("B");
        bg.add(Label_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 18, 20));

        Label_C.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_C.setForeground(new java.awt.Color(255, 102, 0));
        Label_C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_C.setText("C");
        bg.add(Label_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        Label_D.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_D.setForeground(new java.awt.Color(255, 102, 0));
        Label_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_D.setText("D");
        bg.add(Label_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, 20));

        Label_E.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_E.setForeground(new java.awt.Color(255, 102, 0));
        Label_E.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_E.setText("E");
        bg.add(Label_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 17, 20));

        Label_F.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_F.setForeground(new java.awt.Color(255, 102, 0));
        Label_F.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_F.setText("F");
        bg.add(Label_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, 17, 30));

        Label_1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_1.setForeground(new java.awt.Color(255, 102, 0));
        Label_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_1.setText("1");
        bg.add(Label_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        Label_2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_2.setForeground(new java.awt.Color(255, 102, 0));
        Label_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_2.setText("2");
        bg.add(Label_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        Label_3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_3.setForeground(new java.awt.Color(255, 102, 0));
        Label_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_3.setText("3");
        bg.add(Label_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        Label_4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_4.setForeground(new java.awt.Color(255, 102, 0));
        Label_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_4.setText("4");
        bg.add(Label_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        Label_5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_5.setForeground(new java.awt.Color(255, 102, 0));
        Label_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_5.setText("5");
        bg.add(Label_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        Label_6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_6.setForeground(new java.awt.Color(255, 102, 0));
        Label_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_6.setText("6");
        bg.add(Label_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        Label_7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_7.setForeground(new java.awt.Color(255, 102, 0));
        Label_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_7.setText("7");
        bg.add(Label_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        Label_8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_8.setForeground(new java.awt.Color(255, 102, 0));
        Label_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_8.setText("8");
        bg.add(Label_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        Label_9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_9.setForeground(new java.awt.Color(255, 102, 0));
        Label_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_9.setText("9");
        bg.add(Label_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        Label_10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_10.setForeground(new java.awt.Color(255, 102, 0));
        Label_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_10.setText("10");
        bg.add(Label_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 50, -1));

        Label_11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_11.setForeground(new java.awt.Color(255, 102, 0));
        Label_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_11.setText("11");
        bg.add(Label_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 50, -1));

        confirmpanel.setBackground(new java.awt.Color(255, 102, 0));
        confirmpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_seat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8_sleeper_chair_52px_1.png"))); // NOI18N
        btn_seat.setContentAreaFilled(false);
        btn_seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seatActionPerformed(evt);
            }
        });
        confirmpanel.add(btn_seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 109, 60, -1));

        Label_Confirm.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        Label_Confirm.setForeground(new java.awt.Color(204, 204, 204));
        Label_Confirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Confirm.setText("CONFIRM");
        confirmpanel.add(Label_Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 176, 60, -1));

        bg.add(confirmpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 18, 70, 330));

        enter.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        enter.setForeground(new java.awt.Color(204, 204, 204));
        bg.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 20, 10));

        F1.setBackground(java.awt.Color.green);
        F1.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F1.setText("F1");
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 50, -1));

        F2.setBackground(java.awt.Color.green);
        F2.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F2.setText("F2");
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 50, -1));

        F3.setBackground(java.awt.Color.green);
        F3.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F3.setText("F3");
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 50, -1));

        F4.setBackground(java.awt.Color.green);
        F4.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F4.setText("F4");
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 50, -1));

        F5.setBackground(java.awt.Color.green);
        F5.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F5.setText("F5");
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 50, -1));

        F6.setBackground(java.awt.Color.green);
        F6.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F6.setText("F6");
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 50, -1));

        F7.setBackground(java.awt.Color.green);
        F7.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F7.setText("F7");
        F7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 50, -1));

        F8.setBackground(java.awt.Color.green);
        F8.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F8.setText("F8");
        F8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 50, -1));

        F9.setBackground(java.awt.Color.green);
        F9.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F9.setText("F9");
        F9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 50, -1));

        F10.setBackground(java.awt.Color.green);
        F10.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F10.setText("F10");
        F10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 50, -1));

        F11.setBackground(java.awt.Color.green);
        F11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        F11.setText("F11");
        F11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(F11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 50, -1));

        E1.setBackground(java.awt.Color.green);
        E1.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E1.setText("E1");
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 50, -1));

        E2.setBackground(java.awt.Color.green);
        E2.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E2.setText("E2");
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 50, -1));

        E3.setBackground(java.awt.Color.green);
        E3.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E3.setText("E3");
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, -1));

        E4.setBackground(java.awt.Color.green);
        E4.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E4.setText("E4");
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 50, -1));

        E5.setBackground(java.awt.Color.green);
        E5.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E5.setText("E5");
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, -1));

        E6.setBackground(java.awt.Color.green);
        E6.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E6.setText("E6");
        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 50, -1));

        E7.setBackground(java.awt.Color.green);
        E7.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E7.setText("E7");
        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 50, -1));

        E8.setBackground(java.awt.Color.green);
        E8.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E8.setText("E8");
        E8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 50, -1));

        E9.setBackground(java.awt.Color.green);
        E9.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E9.setText("E9");
        E9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 50, -1));

        E10.setBackground(java.awt.Color.green);
        E10.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E10.setText("E10");
        E10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 50, -1));

        E11.setBackground(java.awt.Color.green);
        E11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        E11.setText("E11");
        E11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(E11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 50, -1));

        D1.setBackground(java.awt.Color.green);
        D1.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D1.setText("D1");
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        D2.setBackground(java.awt.Color.green);
        D2.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D2.setText("D2");
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, -1));

        D3.setBackground(java.awt.Color.green);
        D3.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D3.setText("D3");
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, -1));

        D4.setBackground(java.awt.Color.green);
        D4.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D4.setText("D4");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 50, -1));

        D5.setBackground(java.awt.Color.green);
        D5.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D5.setText("D5");
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 50, -1));

        D6.setBackground(java.awt.Color.green);
        D6.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D6.setText("D6");
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 50, -1));

        D7.setBackground(java.awt.Color.green);
        D7.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D7.setText("D7");
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 50, -1));

        D8.setBackground(java.awt.Color.green);
        D8.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D8.setText("D8");
        D8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 50, -1));

        D9.setBackground(java.awt.Color.green);
        D9.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D9.setText("D9");
        D9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 50, -1));

        D10.setBackground(java.awt.Color.green);
        D10.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D10.setText("D10");
        D10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 50, -1));

        D11.setBackground(java.awt.Color.green);
        D11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        D11.setText("D11");
        D11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(D11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 50, -1));

        C1.setBackground(java.awt.Color.green);
        C1.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C1.setText("C1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        C2.setBackground(java.awt.Color.green);
        C2.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C2.setText("C2");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 50, -1));

        C3.setBackground(java.awt.Color.green);
        C3.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C3.setText("C3");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 50, -1));

        C4.setBackground(java.awt.Color.green);
        C4.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C4.setText("C4");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 50, -1));

        C5.setBackground(java.awt.Color.green);
        C5.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C5.setText("C5");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 50, -1));

        C6.setBackground(java.awt.Color.green);
        C6.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C6.setText("C6");
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, -1));

        C7.setBackground(java.awt.Color.green);
        C7.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C7.setText("C7");
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 50, -1));

        C8.setBackground(java.awt.Color.green);
        C8.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C8.setText("C8");
        C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 50, -1));

        C9.setBackground(java.awt.Color.green);
        C9.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C9.setText("C9");
        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 50, -1));

        C10.setBackground(java.awt.Color.green);
        C10.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C10.setText("C10");
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 50, -1));

        C11.setBackground(java.awt.Color.green);
        C11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        C11.setText("C11");
        C11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 50, -1));

        B1.setBackground(java.awt.Color.green);
        B1.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, -1));

        B2.setBackground(java.awt.Color.green);
        B2.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 50, -1));

        B3.setBackground(java.awt.Color.green);
        B3.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, -1));

        B4.setBackground(java.awt.Color.green);
        B4.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 50, -1));

        B5.setBackground(java.awt.Color.green);
        B5.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B5.setText("B5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 50, -1));

        B6.setBackground(java.awt.Color.green);
        B6.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B6.setText("B6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 50, -1));

        B7.setBackground(java.awt.Color.green);
        B7.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B7.setText("B7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 50, -1));

        B8.setBackground(java.awt.Color.green);
        B8.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B8.setText("B8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 50, -1));

        B9.setBackground(java.awt.Color.green);
        B9.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B9.setText("B9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 50, -1));

        B10.setBackground(java.awt.Color.green);
        B10.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B10.setText("B10");
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 50, -1));

        B11.setBackground(java.awt.Color.green);
        B11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        B11.setText("B11");
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 50, -1));

        A1.setBackground(java.awt.Color.green);
        A1.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, -1));

        A2.setBackground(java.awt.Color.green);
        A2.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, -1));

        A3.setBackground(java.awt.Color.green);
        A3.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, -1));

        A4.setBackground(java.awt.Color.green);
        A4.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 50, -1));

        A5.setBackground(java.awt.Color.green);
        A5.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A5.setText("A5");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, -1));

        A6.setBackground(java.awt.Color.green);
        A6.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 50, -1));

        A7.setBackground(java.awt.Color.green);
        A7.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A7.setText("A7");
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 50, -1));

        A8.setBackground(java.awt.Color.green);
        A8.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A8.setText("A8");
        A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 50, -1));

        A9.setBackground(java.awt.Color.green);
        A9.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A9.setText("A9");
        A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 50, -1));

        A10.setBackground(java.awt.Color.green);
        A10.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A10.setText("A10");
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 50, 20));

        A11.setBackground(java.awt.Color.green);
        A11.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        A11.setText("A11");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClicked(evt);
            }
        });
        bg.add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 50, -1));

        ico_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/icons8_delete_30px.png"))); // NOI18N
        ico_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_ExitMouseClicked(evt);
            }
        });
        bg.add(ico_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 45, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<String> deleteElementArrayList(ArrayList<String> array, String value) {
        for (int i = 0; i < array.size(); i++) {
            if (array.get(i).equals(value)) {
                array.remove(i);
                break;
            }
        }
        return array;
    }
    private void btn_seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seatActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < seat.size(); i++) {
            Strseat += seat.get(i) + ",";
        }
        Strseat = Strseat.substring(0, Strseat.length() - 1);
        Strseat = Strseat.substring(4);
        tc.TextField_SeatSelected.setText(Strseat);
        int price = Integer.parseInt(tc.TextField_Price.getText());
        int qty = seat.size();
        int totalPrice = qty * price;
        tc.TextField_TotalPrice.setText(Integer.toString(totalPrice));
        tc.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_seatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String qry = "SELECT\n"
                + "tickets.SeatNo\n"
                + "FROM\n"
                + "tickets\n"
                + "WHERE\n"
                + "tickets.ScheduleID = '"+scheduleid+"'";
        ResultSet rs = AFAUtils.Select(qry);
        try {
            while (rs.next()) {
                String seatno = rs.getString("SeatNo");
                JButton seatButton = Awt1.getComponentByName(this, seatno);
                seatButton.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectSeat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void ButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClicked
        // TODO add your handling code here:
        JButton bpress = (JButton) evt.getSource();
        if (bpress.getBackground() == Color.red) {
            bpress.setBackground(Color.green);
            seat = deleteElementArrayList(seat, bpress.getText());
        } else {
            if (seat.size() >= 10) {
                JOptionPane.showMessageDialog(null,
                        "You can only choose Max 10 seat",
                        "Error",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                bpress.setBackground(Color.red);
                seat.add(bpress.getText());
            }
        }
    }//GEN-LAST:event_ButtonClicked

    private void ico_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        tc.setVisible(true);
    }//GEN-LAST:event_ico_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C11;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JButton D1;
    private javax.swing.JButton D10;
    private javax.swing.JButton D11;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton D9;
    private javax.swing.JButton E1;
    private javax.swing.JButton E10;
    private javax.swing.JButton E11;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton E9;
    private javax.swing.JButton F1;
    private javax.swing.JButton F10;
    private javax.swing.JButton F11;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton F9;
    private javax.swing.JLabel Label_1;
    private javax.swing.JLabel Label_10;
    private javax.swing.JLabel Label_11;
    private javax.swing.JLabel Label_2;
    private javax.swing.JLabel Label_3;
    private javax.swing.JLabel Label_4;
    private javax.swing.JLabel Label_5;
    private javax.swing.JLabel Label_6;
    private javax.swing.JLabel Label_7;
    private javax.swing.JLabel Label_8;
    private javax.swing.JLabel Label_9;
    private javax.swing.JLabel Label_A;
    private javax.swing.JLabel Label_B;
    private javax.swing.JLabel Label_C;
    private javax.swing.JLabel Label_Confirm;
    private javax.swing.JLabel Label_D;
    private javax.swing.JLabel Label_E;
    private javax.swing.JLabel Label_F;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_seat;
    private javax.swing.JPanel confirmpanel;
    private javax.swing.JLabel enter;
    private javax.swing.JLabel ico_Exit;
    // End of variables declaration//GEN-END:variables
}
